### ISSUE TITLE
add brussels

### ISSUE THREAD

**Issue by tbueno** [gtfs-collection/overview#230]
city=brussels_belgium,url=http://gtfs.irail.be/mivb/mivb-gtfs.zip

**Comment by ustroetz** [comment]
There was an error while uploading the file stop_times.txt. The repository will be deleted again.

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
Repository already exists

**Comment by ustroetz** [comment]
There was an error while uploading the file stop_times.txt. The repository will be deleted again.

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
The given url is invalid.

**Comment by ustroetz** [comment]
There was an error while uploading the file stop_times.txt. The repository will be deleted again.
