### ISSUE TITLE
add mexico city

### ISSUE THREAD

**Issue by ustroetz** [gtfs-collection/overview#39]
city=mexico-city_mexico,url=https://s3.amazonaws.com/setravi/df_gtfs.zip

**Comment by gtfs-collection** [comment]
Repository created and GTFS feed added

**Comment by gtfs-collection** [comment]
mexico-city_mexico was added to places.geojson with the coordinates [19.4326077, -99.133208]

**Comment by gtfs-collection** [comment]
mexico-city_mexico was added to README.md
