### ISSUE TITLE
add sao paulo

### ISSUE THREAD

**Issue by ustroetz** [gtfs-collection/overview#40]
city=sao-paulo_brazil,url=http://bit.ly/1NcJg1c

**Comment by gtfs-collection** [comment]
Repository created and GTFS feed added

**Comment by gtfs-collection** [comment]
sao-paulo_brazil was added to places.geojson with the coordinates [-23.5505199, -46.63330939999999]

**Comment by gtfs-collection** [comment]
sao-paulo_brazil was added to README.md

**Comment by ustroetz** [comment]
City polygon was added to the polygon directory in the overview repository

**Comment by ustroetz** [comment]
There was an error while uploading the file __MACOSX/._fare_rules.txt. The repository will be deleted again.

**Comment by ustroetz** [comment]
A specified parameter was not correct

**Comment by ustroetz** [comment]
A specified parameter was not correct

**Comment by ustroetz** [comment]
City polygon was added to the polygon directory in the overview repository

**Comment by ustroetz** [comment]
Repository created and GTFS feed added

**Comment by ustroetz** [comment]
sao-paulo_brazil was added to places.geojson with the coordinates [-23.5505199, -46.63330939999999]

**Comment by ustroetz** [comment]
City polygon was added to the polygon directory in the overview repository

**Comment by ustroetz** [comment]
Repository created and GTFS feed added

**Comment by ustroetz** [comment]
sao-paulo_brazil was added to places.geojson with the coordinates [-23.5505199, -46.63330939999999]
