### ISSUE TITLE
add porto alegre

### ISSUE THREAD

**Issue by tbueno** [gtfs-collection/overview#53]
city=porto-alegre_brazil,url=http://datapoa.com.br/storage/f/2014-08-22T14%3A37%3A23.272Z/outputfiles.zip

**Comment by ustroetz** [comment]
There was an error while uploading the file calendar_dates.txt. The repository will be deleted again.

**Comment by ustroetz** [comment]
There was an error while uploading the file routes.txt. The repository will be deleted again.

**Comment by ustroetz** [comment]
Repository created and GTFS feed added

**Comment by ustroetz** [comment]
City polygon was added to the polygon directory in the overview repository

**Comment by ustroetz** [comment]
Repository already exists

**Comment by ustroetz** [comment]
The given parameters are invalid.

**Comment by ustroetz** [comment]
There was an error while uploading the file stop_times.txt. The repository will be deleted again.

**Comment by ustroetz** [comment]
There was an error while uploading the file stop_times.txt. The repository will be deleted again.

**Comment by ustroetz** [comment]
City added.
