### ISSUE TITLE
Belo Horizonte, Brazil

### ISSUE THREAD

**Issue by tbueno** [gtfs-collection/overview#90]
city=belo-horizonte_brazil,url=http://servicosbhtrans.pbh.gov.br/transitfiles/gtfs_bhtransit.zip

**Comment by ustroetz** [comment]
Repository created and GTFS feed added

**Comment by ustroetz** [comment]
City polygon was added to the polygon directory in the overview repository

**Comment by ustroetz** [comment]
belo-horizonte_brazil was added to places.geojson with the coordinates [-19.9166813, -43.9344931]
